

name = "string"                                 , "Navn på site"
siteID = "string"                               , "Navn på site"
IP_adress = "string"                            , "Site ip adresse"
Effective_instalation_date = "date"             , "Dato X ble installert"
BBU_Solution_aspercontract = "int"              , "?"
BBU_solution_ = "string"                        , "?"
TestTimeInHour = "float"                        , "Tid test tok i timer"
TestTimeinMin = "int"                           , "tid test tok i minutter"
RestPercentage = "float"                        , "?"
Restcapacity = "float"                          , "?"
Batt_load = "int"                               , "?"
monthSinceInstall = "int"                       , "måneder siden X ble installert"
Phase = "int/index"                             , "fase på ringen"
SA = "int"                                      , "?"
loc = "string"                                  , "navn på site"
ip = "ip"                                       , "ip til site"
ac = "int/bool"                                 , "?"
test = "int/bool"                               , "?"
time = "date"                                   , "?"
battV = "int"                                   , "?"
totcur = "int"                                  , "?"
batcur = "int"                                  , "?"
startEventtime = "date"                         , "start tid på ?"
endEventtime = "date"                           , "sluttid på ?"
endEventbattV = "int"                           , "? etter ?"
endeventbattcur = "int"                         , "? etter ?"
origin = "int/bool"                             , "?"
t1 = "date"                                     , "?"
battv1 = "int"                                  , "?"
t2 = "date"                                     , "?"
battv2 = "int"                                  , "?"
batttemp = "int"                                , "max/avg/min/? batteritemperatur"


# ark 2 og 3

name2 = "string"                                , "Navn på site"
site_id = "string"                              , "navn på site"
TestTime = "int"                                , "Test tid"
MOT_BSSubnet = "ip"                             , "?"
TransmissionOrder = "int"                       , "?"
TransmissionCount = "int"                       , "?"
MOT_BBU_AsPerContract = "string"                , "?"
MOT_APS = "bool/string"                         , "?"
ring = "string"                                 , "navn på ring"
MTS_CRID = "string"                             , "?"
Region_phase_int = "int"                        , "?"
REGION_SA_SHORT =  "string"                     , "sted / ?"


